/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package velhatest;

/**
 *
 * @author Patric
 */
public class Game extends javax.swing.JFrame {
    
    public boolean jogaa = true;
    public boolean jogab = true;
    public int contposi =0;
    public int k=0,i=0;
    int op;
    
    public String linha1,linha2,linha3,coluna1,coluna2,coluna3,diagonal1,error;
    String[][]posvetor = new String[3][3];

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bot1 = new javax.swing.JButton();
        bot2 = new javax.swing.JButton();
        bot3 = new javax.swing.JButton();
        bot4 = new javax.swing.JButton();
        bot5 = new javax.swing.JButton();
        bot6 = new javax.swing.JButton();
        bot7 = new javax.swing.JButton();
        bot8 = new javax.swing.JButton();
        bot9 = new javax.swing.JButton();
        bot10Reiniciar = new javax.swing.JButton();
        txtvisor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bot1.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot1ActionPerformed(evt);
            }
        });

        bot2.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot2ActionPerformed(evt);
            }
        });

        bot3.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot3ActionPerformed(evt);
            }
        });

        bot4.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot4ActionPerformed(evt);
            }
        });

        bot5.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot5ActionPerformed(evt);
            }
        });

        bot6.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot6ActionPerformed(evt);
            }
        });

        bot7.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot7ActionPerformed(evt);
            }
        });

        bot8.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot8ActionPerformed(evt);
            }
        });

        bot9.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        bot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot9ActionPerformed(evt);
            }
        });

        bot10Reiniciar.setText("Reiniciar");
        bot10Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot10ReiniciarActionPerformed(evt);
            }
        });

        txtvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bot2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bot3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bot4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bot5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bot6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bot10Reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bot7, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bot9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bot3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bot6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bot9, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(bot7, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(bot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(txtvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bot10Reiniciar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //metod  que irá fazer a verificação da última jogada.
    public void testPlayerdavez(){
        if(jogaa == true && jogab){
            this.op = 1;
            jogaa = false;
            jogab = true;
            txtvisor.setText("Vez do jogador O");
        } else if(jogaa && jogab == false){
            this.op = 1;
            jogaa = false;
            jogab = true;
            txtvisor.setText("Vez do jogador O");            
        } else{
            this.op = 2;
            jogaa = true;
            jogab = false;
            txtvisor.setText("Vez do jogador X");  
            
        }
    }
    
    public void Limparposicoes(){
        for(i=0; i<3; i++){
            for(k=0; k<3; i++){
                posvetor[i][k]= "";
                System.out.println(posvetor[i][k]);
            }
        }
    }
    
    private void OutBotton(){
        bot1.setEnabled(false);
        bot2.setEnabled(false);
        bot3.setEnabled(false);
        bot4.setEnabled(false);
        bot5.setEnabled(false);
        bot6.setEnabled(false);
        bot7.setEnabled(false);
        bot8.setEnabled(false);
        bot9.setEnabled(false);
    }
    public void Vencedor(){
        linha1 = posvetor[0][0]+ posvetor[0][1]+posvetor[0][2];
        linha2 = posvetor[1][0]+ posvetor[1][1]+posvetor[1][2];
        linha3 = posvetor[2][0]+ posvetor[2][1]+posvetor[2][2];
        
        coluna1 = posvetor[0][0]+ posvetor[1][0]+posvetor[2][0];
        coluna2 = posvetor[0][1]+ posvetor[1][1]+posvetor[2][1];
        coluna3 = posvetor[0][2]+ posvetor[1][2]+posvetor[2][2];
        
        diagonal1 = posvetor[0][0]+posvetor[1][1]+posvetor[2][2];
        error = posvetor[0][2]+posvetor[1][1]+posvetor[2][0];
        
        if(linha1.equals("xxx")|linha2.equals("xxx")|linha3.equals("xxx")|coluna1.equals("xxx")|coluna2.equals("xxx")|diagonal1.equals("xxx")|error.equals("xxx")){
            txtvisor.setText("Player X win");
            OutBotton();
        } else if (linha1.equals("OOO")|linha2.equals("OOO")|linha3.equals("OOO")|coluna1.equals("OOO")|coluna2.equals("OOO")|diagonal1.equals("OOO")|error.equals("OOO")){
            txtvisor.setText("Player O win");
            OutBotton();
        } else if (contposi == 9){
            txtvisor.setText("Vcs São ruinnns '-'");
        }
            
    }
    
    /*private void Deuvelha(){
        contposi =0;
        for(i=0; i<3; i++){
            for(k=0; k<3; i++){
                if(posvetor[i][k] == "x" | posvetor[i][k] == "o"){
                    contpos+=1;
                    System.out.println(posvetor[i][k]);
                }
            }
        }
    }*/
    
    
    
    private void bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot1ActionPerformed
        // TODO add your handling code here:Bot1
        testPlayerdavez();
        if(op == 1){
            bot1.setText("X");
            posvetor[0][0] = "x";
        }else{
            bot1.setText("O");
            posvetor[0][0] = "O";
        }
        
        bot1.setEnabled(false);
        
        Vencedor();
    }//GEN-LAST:event_bot1ActionPerformed
    
    
    private void bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot2ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot2.setText("X");
            posvetor[0][1] = "x";
        }else{
            bot2.setText("O");
            posvetor[0][1] = "O";
        }
        
        bot2.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot2ActionPerformed

    private void bot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot3ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot3.setText("X");
            posvetor[0][2] = "x";
        }else{
            bot3.setText("O");
            posvetor[0][2] = "O";
        }
        
        bot3.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot3ActionPerformed

    private void bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot4ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot4.setText("X");
            posvetor[1][0] = "x";
        }else{
            bot4.setText("O");
            posvetor[1][0] = "O";
        }
        
        bot4.setEnabled(false);
        Vencedor();
        
    }//GEN-LAST:event_bot4ActionPerformed

    private void bot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot5ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot5.setText("X");
            posvetor[1][1] = "x";
        }else{
            bot5.setText("O");
            posvetor[1][1] = "O";
        }
        
        bot5.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot5ActionPerformed

    private void bot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot6ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot6.setText("X");
            posvetor[1][2] = "x";
        }else{
            bot6.setText("O");
            posvetor[1][2] = "O";
        }
        
        bot6.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot6ActionPerformed

    private void bot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot7ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot7.setText("X");
            posvetor[2][1] = "x";
        }else{
            bot7.setText("O");
            posvetor[2][1] = "O";
        }
        
        bot7.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot7ActionPerformed

    private void bot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot8ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot8.setText("X");
            posvetor[2][0] = "x";
        }else{
            bot8.setText("O");
            posvetor[2][0] = "O";
        }
        
        bot8.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot8ActionPerformed

    private void bot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot9ActionPerformed
        // TODO add your handling code here:
        testPlayerdavez();
        if(op == 1){
            bot9.setText("X");
            posvetor[2][2] = "x";
        }else{
            bot9.setText("O");
            posvetor[2][2] = "O";
        }
        
        bot9.setEnabled(false);
        Vencedor();
    }//GEN-LAST:event_bot9ActionPerformed

    private void bot10ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot10ReiniciarActionPerformed
        // TODO add your handling code here:
        bot1.setText("");
        bot1.setEnabled(true);
        
        bot2.setText("");
        bot2.setEnabled(true);
        
        bot3.setText("");
        bot3.setEnabled(true);
        
        bot4.setText("");
        bot4.setEnabled(true);
        
        bot5.setText("");
        bot5.setEnabled(true);
        
        bot6.setText("");
        bot6.setEnabled(true);
        
        bot7.setText("");
        bot7.setEnabled(true);
        
        bot8.setText("");
        bot8.setEnabled(true);
        
        bot9.setText("");
        bot9.setEnabled(true);
        
        Limparposicoes();
        txtvisor.setText("");
                
    }//GEN-LAST:event_bot10ReiniciarActionPerformed

    private void txtvisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvisorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot1;
    private javax.swing.JButton bot10Reiniciar;
    private javax.swing.JButton bot2;
    private javax.swing.JButton bot3;
    private javax.swing.JButton bot4;
    private javax.swing.JButton bot5;
    private javax.swing.JButton bot6;
    private javax.swing.JButton bot7;
    private javax.swing.JButton bot8;
    private javax.swing.JButton bot9;
    private javax.swing.JButton txtvisor;
    // End of variables declaration//GEN-END:variables
}
